[package]

name = "resources_package_package"
version = "0.0.5"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "Apache-2.0"
description = "Utility for the resources_package library"

[lib]
name = "resources_package_package"
path = "src/lib.rs"
